# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 08:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pgm4app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('q', 'question'), ('answer', 'a'), ('c', 'comment')], editable=False, max_length=1)),
                ('slug', models.SlugField(blank=True, default='')),
                ('title', models.CharField(error_messages={'blank': 'Please write a question.'}, help_text='Please write a question.', max_length=200, validators=[pgm4app.models.validate_is_question], verbose_name='question')),
                ('text', models.TextField(blank=True, default='', help_text='Explain what sort of answers you are looking for.', max_length=100000, verbose_name='description')),
                ('ip', models.GenericIPAddressField(blank=True, default=None, editable=False, null=True)),
                ('is_hidden', models.BooleanField(default=False, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('up', models.PositiveIntegerField(default=0)),
                ('down', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('timepoints', models.BigIntegerField(default=0, editable=False)),
                ('parent', models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pgm4app.Content')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'Please write a question.'}, help_text='A tag has only letters or numbers.', max_length=30, verbose_name='tag')),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(related_name='content', to='pgm4app.Tag'),
        ),
        migrations.AddField(
            model_name='content',
            name='user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_content', to=settings.AUTH_USER_MODEL),
        ),
    ]
