# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgm4app', '0003_auto_20160501_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='count_answers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='count_comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='count_favorite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='count_flags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='count_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
