# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgm4app', '0004_auto_20160501_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='edited',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='last_answered',
            field=models.DateTimeField(default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='content', to='pgm4app.Tag'),
        ),
    ]
